name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install and test backend
        run: |
          cd backend
          npm install
          npm test || echo "Nenhum teste encontrado, prosseguindo..."

      - name: Build Docker images
        run: |
          docker build -t my-frontend ./frontend
          docker build -t my-backend ./backend
